module.exports = [
    "abzugshaube",
    "beleuchtung",
    "bewässerung",
    "bügeleisen",
    "deckenspot",
    "drücker",
    "fenster",
    "fernseher",
    "fön",
    "garagentor",
    "gartentor",
    "große stehlampe",
    "haartrockner",
    "hängelampe",
    "haustür",
    "heizkörper",
    "heizung",
    "herd",
    "jalousie",
    "kaffeemaschine",
    "kleine stehlampe",
    "klima",
    "klimaanlage",
    "lampe",
    "lautsprecher",
    "ledleiste",
    "licht",
    "lichtleiste",
    "lüfter",
    "lüftung",
    "luster",
    "markise",
    "markisen",
    "maskierung",
    "microphone",
    "musik",
    "musikanlage",
    "player",
    "poolheizung",
    "poolpumpe",
    "pumpe",
    "raffstore",
    "rechner",
    "rolladen",
    "sat-receiver",
    "schloss",
    "sonos",
    "spülmaschine",
    "stehlampe",
    "temperatur",
    "tor",
    "trockner",
    "tür",
    "tv",
    "verstärker",
    "vorhänge",
    "wandlampe",
    "waschmaschine",
    "wasser",
    "wasserkocher",
    "temperature",
    "led",
    "led stripe",
    "blind",
    "blinds",
    "dimmer",

    "hood",
    "lighting",
    "irrigation",
    "iron",
    "ceiling spot",
    "lever",
    "window",
    "tv",
    "hairdryer",
    "garage",
    "all lights",
    "gates",
    "large floor lamp",
    "hairdryer",
    "hanging lamp",
    "front door",
    "thermostat",
    "weather",
    "shutters",
    "radiator",
    "leds",
    "heater",
    "cooker",
    "louvre",
    "coffee machine",
    "small spotlight",
    "climate",
    "air conditioner",
    "lamp",
    "speaker",
    "led",
    "light",
    "light bar",
    "fan",
    "ventilation",
    "chandelier",
    "awning",
    "awning",
    "masking",
    "microphone",
    "music",
    "stereo",
    "player",
    "heating",
    "pool heating",
    "pool pump",
    "pump",
    "venetian blind",
    "calculator",
    "shutters",
    "satellite receiver",
    "lock",
    "sonos",
    "dishwasher",
    "floor lamp",
    "temperature",
    "gate",
    "dryer",
    "door",
    "tv",
    "amplifier",
    "curtains",
    "wall lamp",
    "washing machine",
    "water",
    "water heater",
    "window",
    "windows",

    "вытяжка",
    "освещение",
    "полив",
    "железо",
    "потолок спот",
    "рычаг",
    "окно",
    "фен",
    "гараж",
    "ворота",
    "большой торшер",
    "фен",
    "подвесной светильник",
    "радиатор",
    "отопление",
    "печка",
    "затвор",
    "кофе",
    "малый торшер",
    "воздух",
    "кондиционер",
    "лампа",
    "динамик",
    "свет",
    "свет бар",
    "вентилятор",
    "вентиляция",
    "глянец",
    "маркизы",
    "маркизы",
    "маскировка",
    "микрофон",
    "музыка",
    "игрок",
    "отопление",
    "насос",
    "жалюзи",
    "компьютер",
    "жалюзи",
    "спутник",
    "замок",
    "посудомоечная машина",
    "торшер",
    "температура",
    "тор",
    "сушилка",
    "дверь",
    "усилитель",
    "штора",
    "настенный светильник",
    "стиральная машина",
    "вода",
    "чайник",
    "окна",
    "окно"
];