module.exports = [
    "abstellkammer",
    "abstellraum",
    "ankleide",
    "arbeitszimmer",
    "auffahrt",
    "außen",
    "außenbereich",
    "bad",
    "bad wc",
    "balkon",
    "büro",
    "carport",
    "dach",
    "dachboden",
    "dachgeschoss",
    "diele",
    "eingang",
    "eingangsbereich",
    "erdgeschoss",
    "essbereich",
    "esstisch",
    "esszimmer",
    "fitnessraum",
    "flur",
    "gaestezimmer",
    "gallerie",
    "garage",
    "garderobe",
    "garten",
    "gartenhaus",
    "gäste wc",
    "gästezimmer",
    "großes bad",
    "kleines bad",
    "hauswirtschaftsraum",
    "heimkino",
    "heizungsraum",
    "innen",
    "kammer",
    "keller",
    "kellergeschoss",
    "kind",
    "kinderzimmer",
    "kleines bad",
    "korridor",
    "küche",
    "obergeschoss",
    "pool",
    "rückwand",
    "scheune",
    "schlafzimmer",
    "schuppen",
    "schwimmbad",
    "speis",
    "spielzimmer",
    "stiege",
    "technikraum",
    "terrasse",
    "treppe",
    "treppenhaus",
    "umkleideraum",
    "untergeschoss",
    "vorgarten",
    "vorraum",
    "waschraum",
    "wc",
    "werkstätte",
    "windfang",
    "wohnraum",
    "wohnzimmer",
    "Wohnbereich",
    "schlafbereich",
    "essbereich",

    "storeroom",
    "dressing room",
    "study",
    "driveway",
    "outside",
    "exterior",
    "bath",
    "balcony",
    "office",
    "carport",
    "top, roof",
    "attic",
    "hallway",
    "entrance",
    "ground floor",
    "dining area",
    "dining table",
    "dining room",
    "gym",
    "hall",
    "guest room",
    "gallery",
    "garage",
    "wardrobe",
    "garden",
    "garden house",
    "guest wc",
    "guest room",
    "great bathroom",
    "small bathroom",
    "utility room",
    "home theater",
    "boiler room",
    "inside",
    "chamber",
    "cellar",
    "basement",
    "child",
    "nursery",
    "small bathroom",
    "corridor",
    "kitchen",
    "upstairs",
    "pool",
    "backboard",
    "barn",
    "bedroom",
    "shed",
    "swimming pool",
    "food",
    "playroom",
    "stairs",
    "engine room",
    "terrace",
    "stairway",
    "staircase",
    "locker room",
    "basement",
    "front yard",
    "anteroom",
    "washroom",
    "workshop",
    "porch",
    "living room",
    "first floor",
    "second floor",
    "third floor",
    "forth floor",
    "fifth floor",
    "bathroom",
    "child's room",
    "toilet",

    "чулан",
    "гардероб",
    "домашний офис",
    "ванная",
    "балкон",
    "офис",
    "кабинет",
    "навес",
    "крыша",
    "чердак",
    "прихожая",
    "вход",
    "первый этаж",
    "столовая",
    "обеденный стол",
    "столовая",
    "центр",
    "коридор",
    "гостевая комната",
    "гостевая",
    "галерея",
    "гараж",
    "гардероб",
    "сад",
    "летний сад",
    "кровать",
    "большая ванна",
    "малая ванная",
    "кладовка",
    "домашний кинотеатр",
    "котельная",
    "внутри",
    "палата",
    "подвал",
    "детская",
    "детский сад",
    "малая ванная",
    "коридор",
    "кухня",
    "наверху",
    "бассейн",
    "амбар",
    "спальня",
    "хатка",
    "бассейн",
    "продукты питания",
    "лестница",
    "машинный зал",
    "терраса",
    "лестница",
    "раздевалка",
    "подвал",
    "двор",
    "прачечная",
    "мастерская",
    "веранда",
    "гостиная",
    "зал"
];