/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "OpenHAB IP": {                                  "en": "OpenHAB IP",                                      "de": "OpenHAB IP",                                      "ru": "OpenHAB IP",                                      "pt": "IP OpenHAB",                                      "nl": "OpenHAB IP",                                      "fr": "OpenHAB IP",                                      "it": "OpenHAB IP",                                      "es": "OpenHAB IP",                                      "pl": "OpenHAB IP"},
    "OpenHAB Port": {                                "en": "OpenHAB Port",                                    "de": "OpenHAB-Anschluss",                               "ru": "Порт OpenHAB",                                    "pt": "Porta OpenHAB",                                   "nl": "OpenHAB-poort",                                   "fr": "Port OpenHAB",                                    "it": "Porta OpenHAB",                                   "es": "Puerto OpenHAB",                                  "pl": "Port OpenHAB"},
    "OpenHAB path": {                                "en": "OpenHAB path",                                    "de": "OpenHAB-Pfad",                                    "ru": "Путь OpenHAB",                                    "pt": "Caminho OpenHAB",                                 "nl": "OpenHAB-pad",                                     "fr": "Chemin OpenHAB",                                  "it": "Percorso OpenHAB",                                "es": "Ruta OpenHAB",                                    "pl": "Ścieżka OpenHAB"},
    "OpenHAB protocol": {                            "en": "OpenHAB protocol",                                "de": "OpenHAB-Protokoll",                               "ru": "Протокол OpenHAB",                                "pt": "Protocolo OpenHAB",                               "nl": "OpenHAB-protocol",                                "fr": "Protocole OpenHAB",                               "it": "Protocollo OpenHAB",                              "es": "Protocolo OpenHAB",                               "pl": "Protokół OpenHAB"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło"},
    "Reconnect timeout(ms)": {                       "en": "Reconnect timeout(ms)",                           "de": "Zeitlimit für Verbindungswiederherstellung (ms)", "ru": "Тайм-аут повторного подключения (мс)",            "pt": "Reconectar o tempo limite (ms)",                  "nl": "Reconnect time-out (ms)",                         "fr": "Délai de reconnexion (ms)",                       "it": "Timeout di riconnessione (ms)",                   "es": "Reconectar tiempo de espera (ms)",                "pl": "Połącz ponownie limit czasu (ms)"},
    "Username": {                                    "en": "Username",                                        "de": "Nutzername",                                      "ru": "имя пользователя",                                "pt": "Nome de usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika"},
};